print("this is a list")
a = ["ishika", "saksham", "riddhi", "dibyasom"]
print(f"list=> {a}")
print(f"type=> {type(a)}")
print("\n==============================\n")
print("this is a string")
b = "Hey my name is ishika"
print(f"list=> {b}")
print(f"type=> {type(b)}")
print("\n==============================\n")
print("Converting string to list")
c=list(b)
print(f"string to list=> {c}")
print(f"type=> {type(c)}")
print("\n==============================\n")
print("Converting list to string")
d=' '.join(a)
print(f"string to list=> {d}")
print(f"type=> {type(d)}")